### ISSUE TITLE
Unnecessary error logs

### ISSUE THREAD

**Issue by ibrahimsag** [gtaylor/paypal-python#42]
Hey,
The error logs in the following lines seem unnecessary since we are already throwing an exception: https://github.com/gtaylor/paypal-python/blob/master/paypal/interface.py#L118.

Should these be removed? or can we provide a way to block these?
because the following does not seem to work:

```Python
log = logging.getLogger('paypal.interface')
log.setLevel(logging.CRITICAL)
...method call...
log.setLevel(logging.NOTSET)
```

Appreciate any help.

**Comment by gtaylor** [comment]
I'd accept a PR with the logger calls in that try/except block removed.
